//! Work Planner for Clypra Real-Time Media Engine (Phase F)
//!
//! Enforces:
//! - Continuous preparation of upcoming media work before playback deadlines
//! - Priorities: Current (highest) > Next > Lookahead > Background
//! - Direction-aware prefetching (Forward, Reverse, Stationary)
//! - Stale work cancellation tagged with (project_revision, playback_generation)
//! - Explicit separation: The planner never performs GPU commands or rendering.

pub mod cache;
pub mod queue;

use super::render_plan::RenderPlan;
use super::types::MediaTime;
use serde::{Deserialize, Serialize};
use std::time::{Duration, Instant};

pub use cache::{CacheVariant, FrameCacheKey, MediaFrameCache};
pub use queue::{
    PerAssetQueueManager, QueueConfig, ReadyFrame, ReadyFrameQueue, ReadyTimingStatus,
};

/// Fine-grained priority for scheduling decode and cache retrieval tasks.
/// Strictly prevents background work from starving active playback frames.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum MediaPriority {
    /// Background work: offline export, pre-warming, thumbnail caching
    Background = 0,
    /// Far lookahead: prefetching beyond the immediate playback window
    Lookahead = 1,
    /// Near future: frames needed within the next 1-2 vsync intervals
    Next = 2,
    /// Critical: the active frame required for the current presentation deadline
    Current = 3,
}

/// The direction of playback for prefetch lookahead calculation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlaybackDirection {
    Forward,
    Reverse,
    Stationary,
}

/// Time-based prefetch policy configuration.
/// Driven by milliseconds/duration rather than arbitrary frame counts.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PrefetchPolicy {
    /// Time window to buffer ahead during continuous playback (e.g. 200 ms)
    pub playback_window: Duration,
    /// Low-latency window to buffer around current playhead during scrubbing (e.g. 35 ms)
    pub scrub_window: Duration,
    /// Maximum number of requests allowed in flight per stream
    pub max_in_flight_per_stream: usize,
}

impl Default for PrefetchPolicy {
    fn default() -> Self {
        Self {
            playback_window: Duration::from_millis(200),
            scrub_window: Duration::from_millis(35),
            max_in_flight_per_stream: 6,
        }
    }
}

/// Keyframe-aware decode interval for predictive demuxing and decoding.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct DecodeRange {
    /// Nearest preceding keyframe timestamp where decoding must begin
    pub start: MediaTime,
    /// Exact target timestamp requested by the timeline
    pub target: MediaTime,
}

impl DecodeRange {
    pub fn new(start: MediaTime, target: MediaTime) -> Self {
        Self { start, target }
    }

    /// Single-frame range when target is an exact keyframe or Intra-only stream
    pub fn exact(target: MediaTime) -> Self {
        Self {
            start: target,
            target,
        }
    }
}

/// Concrete media decode or cache request generated by the planner.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MediaRequest {
    pub asset_id: String,
    pub source_time: MediaTime,
    pub priority: MediaPriority,
    pub decode_range: DecodeRange,
    pub project_revision: u64,
    pub playback_generation: u64,
}

impl MediaRequest {
    /// Validates if this request is still relevant or obsolete.
    #[inline]
    pub fn is_obsolete(&self, current_revision: u64, current_generation: u64) -> bool {
        self.project_revision != current_revision || self.playback_generation != current_generation
    }
}

/// Result of evaluating or attempting to dispatch a media request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WorkResult {
    /// Request submitted to the decoder queue
    Submitted,
    /// Found directly in the ready frame cache
    CacheHit,
    /// Request was discarded because generation or project revision advanced
    Obsolete(String),
    /// Request could not be fulfilled due to starvation
    Starved(String),
}

/// A comprehensive plan of media work needed to satisfy playback at time T
/// and keep downstream queues continuously populated.
#[derive(Debug, Clone)]
pub struct MediaWorkPlan {
    pub project_revision: u64,
    pub playback_generation: u64,
    pub target_time: MediaTime,
    pub deadline: Instant,
    pub direction: PlaybackDirection,
    pub requests: Vec<MediaRequest>,
}

impl MediaWorkPlan {
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.requests.is_empty()
    }

    #[inline]
    pub fn len(&self) -> usize {
        self.requests.len()
    }

    /// Returns the subset of requests with `MediaPriority::Current`.
    pub fn current_frame_requests(&self) -> impl Iterator<Item = &MediaRequest> {
        self.requests
            .iter()
            .filter(|r| r.priority == MediaPriority::Current)
    }

    /// Returns the lookahead requests sorted by priority (Next before Lookahead).
    pub fn lookahead_requests(&self) -> impl Iterator<Item = &MediaRequest> {
        self.requests
            .iter()
            .filter(|r| r.priority != MediaPriority::Current)
    }
}

/// Comprehensive telemetry metrics capturing work planner and queue behaviors.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PlannerTelemetry {
    pub planner_latency_us: u64,
    pub plan_requests: usize,
    pub cache_hits: u64,
    pub cache_misses: u64,
    pub decode_queue_depth: usize,
    pub ready_queue_depth: usize,
    pub demux_queue_depth: usize,
    pub prefetch_window_ms: u64,
    pub prefetch_hit_ratio: f32,
    pub obsolete_requests: u64,
    pub cancelled_requests: u64,
    pub surface_pool_used: usize,
    pub surface_pool_capacity: usize,
    pub current_frame_wait_us: u64,
    pub next_frame_wait_us: u64,
}

/// Authoritative Media Work Planner.
/// Evaluates RenderPlans and drives the predictive prefetch pipeline.
#[derive(Debug, Clone)]
pub struct WorkPlanner {
    pub policy: PrefetchPolicy,
    pub current_generation: u64,
    pub current_revision: u64,
    pub telemetry: PlannerTelemetry,
}

impl WorkPlanner {
    pub fn new(policy: PrefetchPolicy) -> Self {
        Self {
            policy,
            current_generation: 1,
            current_revision: 1,
            telemetry: PlannerTelemetry::default(),
        }
    }

    pub fn set_version(&mut self, revision: u64, generation: u64) {
        self.current_revision = revision;
        self.current_generation = generation;
    }

    /// Transforms a timeline RenderPlan into a predictive MediaWorkPlan.
    /// Derives upcoming timestamps based on direction and time-based prefetch policy.
    pub fn plan(
        &mut self,
        render_plan: &RenderPlan,
        direction: PlaybackDirection,
        deadline: Instant,
    ) -> MediaWorkPlan {
        let start_time = Instant::now();
        self.current_revision = render_plan.project_revision;
        self.current_generation = render_plan.generation;

        let frame_duration = MediaTime::from_secs_f64(1.0 / render_plan.canvas.fps.max(1.0));
        let mut requests = Vec::new();

        // 1. Plan current active frame layers (Priority: Current)
        for layer in &render_plan.layers {
            if layer.asset_id.is_empty() {
                continue;
            }
            // Keyframe estimation: assume keyframe at least every 1 second (1000ms)
            let gop_micros = 1_000_000i64;
            let keyframe_pts = MediaTime(
                layer.source_time.as_micros() - (layer.source_time.as_micros() % gop_micros),
            );
            let decode_range = DecodeRange::new(keyframe_pts, layer.source_time);

            requests.push(MediaRequest {
                asset_id: layer.asset_id.clone(),
                source_time: layer.source_time,
                priority: MediaPriority::Current,
                decode_range,
                project_revision: self.current_revision,
                playback_generation: self.current_generation,
            });
        }

        // 2. Plan lookahead frames within time-based prefetch window
        let window = match direction {
            PlaybackDirection::Stationary => self.policy.scrub_window,
            _ => self.policy.playback_window,
        };

        let lookahead_frames =
            (window.as_secs_f64() * render_plan.canvas.fps.max(1.0)).round() as usize;

        for step in 1..=lookahead_frames {
            let offset_micros = frame_duration.as_micros() * step as i64;
            let target_time_offset = match direction {
                PlaybackDirection::Forward => offset_micros,
                PlaybackDirection::Reverse => -offset_micros,
                PlaybackDirection::Stationary => 0,
            };

            if target_time_offset == 0 && direction == PlaybackDirection::Stationary {
                break;
            }

            let priority = if step <= 2 {
                MediaPriority::Next
            } else {
                MediaPriority::Lookahead
            };

            for layer in &render_plan.layers {
                if layer.asset_id.is_empty() {
                    continue;
                }
                let lookahead_source_time =
                    MediaTime((layer.source_time.as_micros() + target_time_offset).max(0));
                let gop_micros = 1_000_000i64;
                let keyframe_pts = MediaTime(
                    lookahead_source_time.as_micros()
                        - (lookahead_source_time.as_micros() % gop_micros),
                );
                let decode_range = DecodeRange::new(keyframe_pts, lookahead_source_time);

                requests.push(MediaRequest {
                    asset_id: layer.asset_id.clone(),
                    source_time: lookahead_source_time,
                    priority,
                    decode_range,
                    project_revision: self.current_revision,
                    playback_generation: self.current_generation,
                });
            }
        }

        let elapsed = start_time.elapsed().as_micros() as u64;
        self.telemetry.planner_latency_us = elapsed;
        self.telemetry.plan_requests = requests.len();
        self.telemetry.prefetch_window_ms = window.as_millis() as u64;

        MediaWorkPlan {
            project_revision: self.current_revision,
            playback_generation: self.current_generation,
            target_time: render_plan.time,
            deadline,
            direction,
            requests,
        }
    }

    /// Evaluates if an in-flight request has become obsolete due to revision or generation change.
    pub fn evaluate_request(&mut self, request: &MediaRequest) -> WorkResult {
        if request.project_revision != self.current_revision {
            self.telemetry.cancelled_requests += 1;
            return WorkResult::Obsolete(format!(
                "Project revision changed from {} to {}",
                request.project_revision, self.current_revision
            ));
        }

        if request.playback_generation != self.current_generation {
            self.telemetry.obsolete_requests += 1;
            return WorkResult::Obsolete(format!(
                "Playback generation changed from {} to {}",
                request.playback_generation, self.current_generation
            ));
        }

        WorkResult::Submitted
    }
}
