/**
 * Clypra Text Effect Definition Output
 * Auto-generated by Clypra Text Effect Studio on 2026-05-26
 * Satisfies TextEffectDefinition interface structure
 */

// Re-export types from @clypra-studio/engine for consistency across the codebase
export type { EffectIndexItem, EffectFullDefinition, TextEffectDefinition } from "@clypra-studio/engine";
